### ISSUE TITLE
exception 'Torch not compiled with CUDA enabled' when forcing '--device cuda'

### ISSUE THREAD

**Issue by quarterturn** [bigscience-workshop/petals#193]
Following the install instructions on the README.md into a dedicated conda env, the server throws an exception as follows:

```
python -m petals.cli.run_server bigscience/bloom-petals --device cuda
Jan 10 05:56:52.030 [INFO] Automatic dht prefix: bigscience/bloom-petals
Jan 10 05:56:58.672 [INFO] Connecting to the public swarm, peer_id = 12D3KooWRKGMtAyEzYsqk1fcT4Eu9CC5jd7YeyTHCoQgDcw1nh4i
Jan 10 05:56:58.673 [INFO] Model weights will be loaded in 8-bit format
Traceback (most recent call last):
  File "/home/a/anaconda3/envs/petals/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/a/anaconda3/envs/petals/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/a/anaconda3/envs/petals/lib/python3.10/site-packages/petals/cli/run_server.py", line 213, in <module>
    main()
  File "/home/a/anaconda3/envs/petals/lib/python3.10/site-packages/petals/cli/run_server.py", line 196, in main
    server = Server(
  File "/home/a/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/server.py", line 168, in __init__
    num_blocks = self._choose_num_blocks()
  File "/home/a/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/server.py", line 232, in _choose_num_blocks
    total_memory = torch.cuda.get_device_properties(self.device).total_memory
  File "/home/a/anaconda3/envs/petals/lib/python3.10/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/a/anaconda3/envs/petals/lib/python3.10/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Is it a cudatoolkit version mismatch with what I have?
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:05:00.0 Off |                    0 |
| N/A   31C    P0    26W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:42:00.0 Off |                    0 |
| N/A   33C    P0    25W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by quarterturn** [comment]
Well, I see that the 'conda install' command does install the CPU version:
```
pytorch            pkgs/main/linux-64::pytorch-1.12.1-cpu_py310he8d8e81_0
```

**Comment by scuty2000** [comment]
Hi! I had this issue a few days ago, you can solve it by uninstalling the cpu only version of pytorch and install it using this command:

`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`

Adjust the cuda version as needed.

**Comment by quarterturn** [comment]
Thanks. Indeed, uninstalling pytorch and reinstalling with the following did the trick:
```
conda install pytorch-cuda -c pytorch -c nvidia
```

**Comment by borzunov** [comment]
Thanks for reporting, we'll update the installation instructions accordingly.
